version: "3.3"

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web

  web:
    build: .
    command: >
      sh -c "
          python manage.py collectstatic
          python manage.py makemigrations
          python manage.py migrate
          python manage.py loaddata products
          gunicorn --bind 0.0.0.0:80 pystore.wsgi:application
        "
    volumes:
      - .:/code
    expose:
      - 80
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=djangodb
      - POSTGRES_DB=djangodb
      - POSTGRES_PASSWORD=djangodb
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: null
