version: "3.3"

services:
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - web

  web:
    build: .
    command: python manage.py collectstatic
    command: gunicorn --bind 0.0.0.0:8000 pystore.wsgi:application
    volumes:
      - .:/code
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=djangodb
      - POSTGRES_DB=djangodb
      - POSTGRES_PASSWORD=djangodb
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
